# Copyright 2021 The TensorFlow Quantum Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

apiVersion: v1
kind: Service
metadata:
  name: tensorboard-service
spec:
  type: LoadBalancer
  selector:
    app: qcnn-tensorboard
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qcnn-tensorboard
  labels:
    app: qcnn-tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qcnn-tensorboard
  template:
    metadata:
      labels:
        app: qcnn-tensorboard
    spec:
      restartPolicy: Always
      serviceAccount: <service_account>
      containers:
      - name: tensorboard
        image: <image_registry>
        ports:
        - containerPort: 5001
        command:
        - "tensorboard"
        args:
        - "--logdir=gs://<bucket_name>/<logdir_name>"
        - "--port=5001"
        - "--bind_all"
