# Summary: yamllint configuration for TFQ.
# See https://yamllint.readthedocs.io/ for info about configuration options.

rules:
  line-length:
    # A common occurrence in YAML files is long URLs. The next two settings
    # are not specific to URLs, but help. It saves developer time by not
    # requiring comment directives to disable warnings at every occurrence.
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
