/* Copyright 2020 The TensorFlow Quantum Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#ifndef TFQ_CORE_QSIM_UNITARY_H_
#define TFQ_CORE_QSIM_UNITARY_H_

#include <complex>
#include <memory>

#include "tensorflow/core/lib/core/status.h"
#include "tensorflow_quantum/core/src/circuit.h"

namespace tfq {
namespace qsim {

// Contains the allowed Unitary labels
enum UnitaryType { SLOW };

// Handles calculations of unitary matrices that a circuit enacts.
class Unitary {
 public:
  Unitary(const uint64_t num_qubits, const uint64_t num_threads)
      : state_(NULL),
        size_(4 * (uint64_t{1} << num_qubits) * (uint64_t{1} << num_qubits)),
        num_qubits_(num_qubits),
        num_threads_(num_threads) {}

  // Apply the unitary generated by circuit to this Unitary.
  tensorflow::Status Update(const Circuit& circuit);

  // Returns true if memory for the state has been succesfully allocated
  bool Valid() const;

  // Pointer to the raw state managed by this Unitary
  float* GetRawState() const;

  // The number of entries in this Unitary matrix.
  uint64_t GetDimension() const;

  // Number of qubits this Unitary Matrix acts on.
  uint64_t GetNumQubits() const;

  // Number of threads that can be used by this Unitary.
  uint64_t GetNumThreads() const;

  virtual ~Unitary() {}

  // Get the Unitary type.
  virtual UnitaryType GetType() const = 0;

  // Reserve the memory associated with this Unitary.
  virtual void CreateState() = 0;

  // Free the memory associated with this Unitary.
  virtual void DeleteState() = 0;

  // Function to apply a two qubit gate to the Unitary on indices q0 and q1.
  // Must adhere to big-endian convention of Cirq.
  virtual void ApplyGate2(const unsigned int q0, const unsigned int q1,
                          const float* matrix) = 0;

  // Function to apply a one-qubit gate if there is one qubit in the Unitary.
  // Implementations are given the option to return an error.
  virtual tensorflow::Status ApplyGate1(const float* matrix) = 0;

  // Set to identity matrix.
  virtual void SetIdentity() = 0;

  // Get the amplitude at the given state index.
  virtual std::complex<float> GetEntry(const uint64_t i, const uint64_t j) const = 0;

  // Set the amplitude at the given state index
  virtual void SetEntry(const uint64_t i, const uint64_t j, const std::complex<float>& val) = 0;

 protected:
  float* state_;
  uint64_t size_;
  uint64_t num_qubits_;
  uint64_t num_threads_;
};

}  // namespace qsim
}  // namespace tfq

#endif  // TFQ_CORE_QSIM_UNITARY_H_
