name: Cirq Compatibility

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  consistency:
    name: Nightly Compatibility
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Bazel on CI
        run: ./scripts/ci_install.sh
      - name: Configure CI TF
        run: echo "Y\n" | ./configure.sh
      - name: Install Cirq nightly
        run: pip install -U cirq --pre
      - name: Nightly tests
        run: ./scripts/test_all.sh
