name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not had any activity in a month. Is it stale ?'
        stale-pr-message: 'This PR has not had any activity in a month. Is it stale ?'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
